### ISSUE TITLE
Ubuntu server doesn't have .local folder

### ISSUE THREAD

**Issue by bitinn** [kevva/xdg-trash#10]
originally reported at https://github.com/sindresorhus/trash/issues/25

getting this error when using `trash`:

```
> find ./cache/ -maxdepth 1 -type f -mtime +7 -not -name .gitignore -exec trash {} + && empty-trash

ENOENT: no such file or directory, scandir '/home/dev/.local/share/Trash/files'
```

**Comment by kevva** [comment]
That's weird, so where is your trash folder located?

**Comment by sindresorhus** [comment]
Hmm, shouldn't it try to find it in `/home/.local/share/Trash/files` rather than `/home/dev/.local/share/Trash/files`.

> think we should just remove the file then or how does that play with your trash module?

The whole point of my `trash` module is to delete safely. Even though Ubuntu Server doesn't have a GUI you can still empty the trash with my [`empty-trash`](https://github.com/sindresorhus/empty-trash) module, so I think we should just create the folder if it doesn't exist.

**Comment by kevva** [comment]
Thing is, Ubuntu Server doesn't **have** a trash :P.

**Comment by bitinn** [comment]
Creating a folder might not always be the best choice: consider you are running the command as a user without home directory, say a system user you created for running cron jobs, that user might not have access to other directories, or in case of  `/home/dev/.local/`, creating a user folder might not be desirable.

But I agree deleting outright breaks the safe `trash` promise, so maybe this is an edge case and it should ask user to do some configuration? or just don't support this edge case...
